---
- name: install wildfly
  hosts: all
  become: yes
  tasks:
   - name: install java
     ansible.builtin.apt:
      name: openjdk-11-jdk
      update_cache: yes
      state: present
   - name: create group
     ansible.builtin.group:
      name: wildfly
      state: present
   - name: adduser 
     ansible.builtin.user:
      name: wildfly
      group: wildfly
      create_home: yes
      home: /opt/wildfly
      shell: /sbin/nologin
   - name: download url
     ansible.builtin.get_url:
      url: https://download.jboss.org/wildfly/19.1.0.Final/wildfly-19.1.0.Final.tar.gz
      dest: /tmp
   - name: extract file
     ansible.builtin.unarchive:
      src: /tmp/wildfly-19.1.0.Final.tar.gz
      dest: /opt/
      remote_src: yes
   - name: create symbolic link
     ansible.builtin.file:
      src: /opt/wildfly-19.1.0.Final
      dest: /opt/wildfly/latest 
      owner: wildfly
      group: wildfly
      state: link
   - name: change ownership
     ansible.builtin.file:
      path: /opt/wildfly
      state: directory
      recurse: yes
      owner: wildfly
      group: wildfly
   - name: create a directory
     ansible.builtin.file:
      path: /etc/wildfly
      state: directory
   - name: copy configuration files
     ansible.builtin.copy:
      src: /opt/wildfly/latest/docs/contrib/scripts/systemd/wildfly.conf
      dest: /etc/wildfly/wildfly.conf
      owner: wildfly
      group: wildfly
      remote_src: yes
      mode: '0644'
   - name: copy launch.sh
     ansible.builtin.copy:
      src: /opt/wildfly/latest/docs/contrib/scripts/systemd/launch.sh
      dest: /opt/wildfly/latest/bin/launch.sh
      owner: wildfly
      group: wildfly
      remote_src: yes
      mode: '0644'
   - name: execute shell 
     ansible.builtin.shell: sudo sh -c 'chmod +x /opt/wildfly/latest/bin/*.sh'
   - name: copy service 
     ansible.builtin.copy:
      src: /opt/wildfly/latest/docs/contrib/scripts/systemd/wildfly.service
      dest: /etc/systemd/system/wildfly.service
      remote_src: yes
      owner: wildfly
      group: wildfly
   - name: daemon reload
     ansible.builtin.systemd:
      name: wildfly 
      state: restarted
      daemon_reload: true
      enabled: yes

      
           
                 

