---
- name: install nodejs on centos
  hosts: all
  become: yes
  tasks:
   - name: connect uri
     ansible.builtin.uri: 
      url: "curl -sL https://rpm.nodesource.com/setup_16.x | sudo bash -"
   - name: install nodejs
     yum:
      name: nodejs
      update_cache: yes
      state: present