---
- name: install java multiple versions 11/8
  hosts: all
  become: yes
  vars:
   openjdk_devel: "11"
  tasks:
   - name: java install
     ansible.builtin.yum:
      name: java-{{ openjdk-devel }}-openjdk
      update_cache: yes
      state: present