---
- name: installation wildfly on ubuntu
  hosts: all
  become: yes
  tasks:
   - name: install java
     ansible.builtin.apt:
      name: openjdk-11-jdk
      update_cache: yes
      state: present
   - name: ensure group
     ansible.builtin.group:
      name: wildfly1
      state: present
   - name: add the user
     ansible.builtin.user:
      name: wildfly1
      create_home: true
      group: wildfly1
      home: /opt/wildfly
      shell: /sbin/nologin
      state: present
   - name: download wildfly
     ansible.builtin.get_url:
      url: https://download.jboss.org/wildfly/16.0.0.Final/wildfly-16.0.0.Final.tar.gz
      dest: /tmp
   - name: unarchive file
     ansible.builtin.unarchive:
      src: /tmp/wildfly-16.0.0.Final.tar.gz
      dest: /opt      
      remote_src: yes
   - name: create a symbolic link
     ansible.builtin.file:
      src: /opt/wildfly-16.0.0.Final/
      dest: /opt/wildfly/latest
      owner: wildfly1
      group: wildfly1
      state: link
   - name: changing ownership
     ansible.builtin.file:
      path: /opt/wildfly
      owner: wildfly1
      group: wildfly1
      mode: '0644'
   - name: create a directory
     ansible.builtin.file:
      path: /etc/wildfly
      state: directory
      mode: '0755'
   - name: copy configuration files
     ansible.builtin.copy:
      src: /opt/wildfly/latest/docs/contrib/scripts/systemd/wildfly.conf
      dest: /etc/wildfly/
      remote_src: yes
   - name: copy file launch.sh
     ansible.builtin.copy:
      src: /opt/wildfly/latest/docs/contrib/scripts/systemd/launch.sh
      dest: /opt/wildfly/bin/
      remote_src: yes
   - name: execute shell
     ansible.builtin.shell: 'chmod +x /opt/wildfly/bin/*.sh'
   - name: copy systemd
     ansible.builtin.copy:
      src: /opt/wildfly/latest/docs/contrib/scripts/systemd/wildfly.service
      dest: /etc/systemd/system/
      remote_src: yes
   - name: create systemd
     ansible.builtin.systemd:
      name: wildfly
      daemon_reload: yes
      enabled: yes
      state: restarted